// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const batchCountMembersAndAdmins = `-- name: BatchCountMembersAndAdmins :many
SELECT "organizationId", COUNT(*), COUNT(*) FILTER (WHERE role = $1)
FROM "member"
WHERE "organizationId" = ANY($2::text[])
GROUP BY "organizationId"
`

type BatchCountMembersAndAdminsParams struct {
	Role    string
	Column2 []string
}

type BatchCountMembersAndAdminsRow struct {
	OrganizationId string
	Count          int64
	Count_2        int64
}

// Batch member/admin counts for a page of orgs (used by listTeams).
func (q *Queries) BatchCountMembersAndAdmins(ctx context.Context, arg BatchCountMembersAndAdminsParams) ([]BatchCountMembersAndAdminsRow, error) {
	rows, err := q.db.QueryContext(ctx, batchCountMembersAndAdmins, arg.Role, pq.Array(arg.Column2))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BatchCountMembersAndAdminsRow
	for rows.Next() {
		var i BatchCountMembersAndAdminsRow
		if err := rows.Scan(&i.OrganizationId, &i.Count, &i.Count_2); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAdmins = `-- name: CountAdmins :one
SELECT COUNT(*) FROM "member" WHERE "organizationId" = $1 AND role = $2
`

type CountAdminsParams struct {
	OrganizationId string
	Role           string
}

func (q *Queries) CountAdmins(ctx context.Context, arg CountAdminsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdmins, arg.OrganizationId, arg.Role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMembersAndAdmins = `-- name: CountMembersAndAdmins :one
SELECT COUNT(*), COUNT(*) FILTER (WHERE role = $2)
FROM "member" WHERE "organizationId" = $1
`

type CountMembersAndAdminsParams struct {
	OrganizationId string
	Role           string
}

type CountMembersAndAdminsRow struct {
	Count   int64
	Count_2 int64
}

func (q *Queries) CountMembersAndAdmins(ctx context.Context, arg CountMembersAndAdminsParams) (CountMembersAndAdminsRow, error) {
	row := q.db.QueryRowContext(ctx, countMembersAndAdmins, arg.OrganizationId, arg.Role)
	var i CountMembersAndAdminsRow
	err := row.Scan(&i.Count, &i.Count_2)
	return i, err
}

const countTeamMembers = `-- name: CountTeamMembers :one
SELECT COUNT(*) FROM "member" m JOIN "user" u ON u.id = m."userId"
WHERE m."organizationId" = $1
`

func (q *Queries) CountTeamMembers(ctx context.Context, organizationid string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTeamMembers, organizationid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTeamMembersBySearch = `-- name: CountTeamMembersBySearch :one
SELECT COUNT(*) FROM "member" m JOIN "user" u ON u.id = m."userId"
WHERE m."organizationId" = $1
  AND (u.name ILIKE '%' || $2::text || '%' OR u."vrchatUsername" ILIKE '%' || $2::text || '%' OR u.slug ILIKE '%' || $2::text || '%')
`

type CountTeamMembersBySearchParams struct {
	OrganizationId string
	Column2        string
}

func (q *Queries) CountTeamMembersBySearch(ctx context.Context, arg CountTeamMembersBySearchParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTeamMembersBySearch, arg.OrganizationId, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTeams = `-- name: CountTeams :one

SELECT COUNT(*) FROM "organization"
`

// Team listing (search and no-search variants; LIMIT NULL means no limit).
func (q *Queries) CountTeams(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTeams)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTeamsBySearch = `-- name: CountTeamsBySearch :one
SELECT COUNT(*) FROM "organization"
WHERE name ILIKE '%' || $1::text || '%' OR slug ILIKE '%' || $1::text || '%'
`

func (q *Queries) CountTeamsBySearch(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTeamsBySearch, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrg = `-- name: CreateOrg :one
INSERT INTO "organization" (id, name, slug, logo, "updatedAt")
VALUES (gen_random_uuid()::text, $1, $2, $3, $4) RETURNING id
`

type CreateOrgParams struct {
	Name      string
	Slug      string
	Logo      sql.NullString
	UpdatedAt sql.NullTime
}

func (q *Queries) CreateOrg(ctx context.Context, arg CreateOrgParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createOrg,
		arg.Name,
		arg.Slug,
		arg.Logo,
		arg.UpdatedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteMember = `-- name: DeleteMember :exec
DELETE FROM "member" WHERE "organizationId" = $1 AND "userId" = $2
`

type DeleteMemberParams struct {
	OrganizationId string
	UserId         string
}

func (q *Queries) DeleteMember(ctx context.Context, arg DeleteMemberParams) error {
	_, err := q.db.ExecContext(ctx, deleteMember, arg.OrganizationId, arg.UserId)
	return err
}

const getOrgByID = `-- name: GetOrgByID :one

SELECT id, name, slug, logo, "rankingAverage", "pointsAverage", "seasonRank", "averagePointsPerEvent"
FROM "organization" WHERE id = $1
`

type GetOrgByIDRow struct {
	ID                    string
	Name                  string
	Slug                  string
	Logo                  sql.NullString
	RankingAverage        sql.NullFloat64
	PointsAverage         sql.NullFloat64
	SeasonRank            sql.NullInt32
	AveragePointsPerEvent sql.NullFloat64
}

// Organization lookups.
func (q *Queries) GetOrgByID(ctx context.Context, id string) (GetOrgByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getOrgByID, id)
	var i GetOrgByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Logo,
		&i.RankingAverage,
		&i.PointsAverage,
		&i.SeasonRank,
		&i.AveragePointsPerEvent,
	)
	return i, err
}

const getOrgBySlug = `-- name: GetOrgBySlug :one
SELECT id, name, slug, logo, "rankingAverage", "pointsAverage", "seasonRank", "averagePointsPerEvent"
FROM "organization" WHERE slug = $1
`

type GetOrgBySlugRow struct {
	ID                    string
	Name                  string
	Slug                  string
	Logo                  sql.NullString
	RankingAverage        sql.NullFloat64
	PointsAverage         sql.NullFloat64
	SeasonRank            sql.NullInt32
	AveragePointsPerEvent sql.NullFloat64
}

func (q *Queries) GetOrgBySlug(ctx context.Context, slug string) (GetOrgBySlugRow, error) {
	row := q.db.QueryRowContext(ctx, getOrgBySlug, slug)
	var i GetOrgBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Logo,
		&i.RankingAverage,
		&i.PointsAverage,
		&i.SeasonRank,
		&i.AveragePointsPerEvent,
	)
	return i, err
}

const insertMember = `-- name: InsertMember :exec
INSERT INTO "member" (id, "organizationId", "userId", role)
VALUES (gen_random_uuid()::text, $1, $2, $3)
`

type InsertMemberParams struct {
	OrganizationId string
	UserId         string
	Role           string
}

func (q *Queries) InsertMember(ctx context.Context, arg InsertMemberParams) error {
	_, err := q.db.ExecContext(ctx, insertMember, arg.OrganizationId, arg.UserId, arg.Role)
	return err
}

const listMemberRows = `-- name: ListMemberRows :many

SELECT m."userId", m.role, u.name, u."vrchatUsername", u.slug
FROM "member" m JOIN "user" u ON u.id = m."userId"
WHERE m."organizationId" = $1 ORDER BY m."createdAt" ASC
`

type ListMemberRowsRow struct {
	UserId         string
	Role           string
	Name           string
	VrchatUsername sql.NullString
	Slug           sql.NullString
}

// Membership.
func (q *Queries) ListMemberRows(ctx context.Context, organizationid string) ([]ListMemberRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMemberRows, organizationid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMemberRowsRow
	for rows.Next() {
		var i ListMemberRowsRow
		if err := rows.Scan(
			&i.UserId,
			&i.Role,
			&i.Name,
			&i.VrchatUsername,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMemberRows = `-- name: ListTeamMemberRows :many
SELECT m."userId", m.role, u.name, u."vrchatUsername", u.slug
FROM "member" m JOIN "user" u ON u.id = m."userId"
WHERE m."organizationId" = $1 ORDER BY m."createdAt" ASC
LIMIT NULLIF($2::int, 0) OFFSET $3
`

type ListTeamMemberRowsParams struct {
	OrganizationId string
	Column2        int32
	Offset         int32
}

type ListTeamMemberRowsRow struct {
	UserId         string
	Role           string
	Name           string
	VrchatUsername sql.NullString
	Slug           sql.NullString
}

func (q *Queries) ListTeamMemberRows(ctx context.Context, arg ListTeamMemberRowsParams) ([]ListTeamMemberRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTeamMemberRows, arg.OrganizationId, arg.Column2, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamMemberRowsRow
	for rows.Next() {
		var i ListTeamMemberRowsRow
		if err := rows.Scan(
			&i.UserId,
			&i.Role,
			&i.Name,
			&i.VrchatUsername,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMemberRowsBySearch = `-- name: ListTeamMemberRowsBySearch :many
SELECT m."userId", m.role, u.name, u."vrchatUsername", u.slug
FROM "member" m JOIN "user" u ON u.id = m."userId"
WHERE m."organizationId" = $1
  AND (u.name ILIKE '%' || $2::text || '%' OR u."vrchatUsername" ILIKE '%' || $2::text || '%' OR u.slug ILIKE '%' || $2::text || '%')
ORDER BY m."createdAt" ASC
LIMIT NULLIF($3::int, 0) OFFSET $4
`

type ListTeamMemberRowsBySearchParams struct {
	OrganizationId string
	Column2        string
	Column3        int32
	Offset         int32
}

type ListTeamMemberRowsBySearchRow struct {
	UserId         string
	Role           string
	Name           string
	VrchatUsername sql.NullString
	Slug           sql.NullString
}

func (q *Queries) ListTeamMemberRowsBySearch(ctx context.Context, arg ListTeamMemberRowsBySearchParams) ([]ListTeamMemberRowsBySearchRow, error) {
	rows, err := q.db.QueryContext(ctx, listTeamMemberRowsBySearch,
		arg.OrganizationId,
		arg.Column2,
		arg.Column3,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamMemberRowsBySearchRow
	for rows.Next() {
		var i ListTeamMemberRowsBySearchRow
		if err := rows.Scan(
			&i.UserId,
			&i.Role,
			&i.Name,
			&i.VrchatUsername,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamRows = `-- name: ListTeamRows :many
SELECT id, name, slug, logo FROM "organization"
ORDER BY name ASC LIMIT NULLIF($1::int, 0) OFFSET $2
`

type ListTeamRowsParams struct {
	Column1 int32
	Offset  int32
}

type ListTeamRowsRow struct {
	ID   string
	Name string
	Slug string
	Logo sql.NullString
}

func (q *Queries) ListTeamRows(ctx context.Context, arg ListTeamRowsParams) ([]ListTeamRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTeamRows, arg.Column1, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamRowsRow
	for rows.Next() {
		var i ListTeamRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Logo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamRowsBySearch = `-- name: ListTeamRowsBySearch :many
SELECT id, name, slug, logo FROM "organization"
WHERE name ILIKE '%' || $1::text || '%' OR slug ILIKE '%' || $1::text || '%'
ORDER BY name ASC LIMIT NULLIF($2::int, 0) OFFSET $3
`

type ListTeamRowsBySearchParams struct {
	Column1 string
	Column2 int32
	Offset  int32
}

type ListTeamRowsBySearchRow struct {
	ID   string
	Name string
	Slug string
	Logo sql.NullString
}

func (q *Queries) ListTeamRowsBySearch(ctx context.Context, arg ListTeamRowsBySearchParams) ([]ListTeamRowsBySearchRow, error) {
	rows, err := q.db.QueryContext(ctx, listTeamRowsBySearch, arg.Column1, arg.Column2, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamRowsBySearchRow
	for rows.Next() {
		var i ListTeamRowsBySearchRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Logo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const memberIDByOrgAndUser = `-- name: MemberIDByOrgAndUser :one
SELECT id FROM "member" WHERE "organizationId" = $1 AND "userId" = $2
`

type MemberIDByOrgAndUserParams struct {
	OrganizationId string
	UserId         string
}

func (q *Queries) MemberIDByOrgAndUser(ctx context.Context, arg MemberIDByOrgAndUserParams) (string, error) {
	row := q.db.QueryRowContext(ctx, memberIDByOrgAndUser, arg.OrganizationId, arg.UserId)
	var id string
	err := row.Scan(&id)
	return id, err
}

const memberRoleByOrgAndUser = `-- name: MemberRoleByOrgAndUser :one
SELECT role FROM "member" WHERE "organizationId" = $1 AND "userId" = $2
`

type MemberRoleByOrgAndUserParams struct {
	OrganizationId string
	UserId         string
}

func (q *Queries) MemberRoleByOrgAndUser(ctx context.Context, arg MemberRoleByOrgAndUserParams) (string, error) {
	row := q.db.QueryRowContext(ctx, memberRoleByOrgAndUser, arg.OrganizationId, arg.UserId)
	var role string
	err := row.Scan(&role)
	return role, err
}

const orgIDByID = `-- name: OrgIDByID :one
SELECT id FROM "organization" WHERE id = $1
`

func (q *Queries) OrgIDByID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, orgIDByID, id)
	err := row.Scan(&id)
	return id, err
}

const orgIDBySlug = `-- name: OrgIDBySlug :one
SELECT id FROM "organization" WHERE slug = $1
`

func (q *Queries) OrgIDBySlug(ctx context.Context, slug string) (string, error) {
	row := q.db.QueryRowContext(ctx, orgIDBySlug, slug)
	var id string
	err := row.Scan(&id)
	return id, err
}

const orgSlugByID = `-- name: OrgSlugByID :one
SELECT slug FROM "organization" WHERE id = $1
`

func (q *Queries) OrgSlugByID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, orgSlugByID, id)
	var slug string
	err := row.Scan(&slug)
	return slug, err
}

const touchOrg = `-- name: TouchOrg :exec
UPDATE "organization" SET "updatedAt" = $1 WHERE id = $2
`

type TouchOrgParams struct {
	UpdatedAt sql.NullTime
	ID        string
}

func (q *Queries) TouchOrg(ctx context.Context, arg TouchOrgParams) error {
	_, err := q.db.ExecContext(ctx, touchOrg, arg.UpdatedAt, arg.ID)
	return err
}

const updateMemberRole = `-- name: UpdateMemberRole :exec
UPDATE "member" SET role = $1 WHERE "organizationId" = $2 AND "userId" = $3
`

type UpdateMemberRoleParams struct {
	Role           string
	OrganizationId string
	UserId         string
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateMemberRole, arg.Role, arg.OrganizationId, arg.UserId)
	return err
}

const updateTeam = `-- name: UpdateTeam :exec
UPDATE "organization"
SET "slug" = $1,
    "updatedAt" = $2,
    "name" = COALESCE($3, "name"),
    "logo" = CASE WHEN $4::boolean THEN NULL ELSE COALESCE($5, "logo") END
WHERE id = $6
`

type UpdateTeamParams struct {
	Slug      string
	UpdatedAt sql.NullTime
	Name      sql.NullString
	ClearLogo bool
	Logo      sql.NullString
	ID        string
}

// Team metadata update. A null name/logo leaves the column unchanged;
// clear_logo forces logo to NULL (explicit clearing).
func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) error {
	_, err := q.db.ExecContext(ctx, updateTeam,
		arg.Slug,
		arg.UpdatedAt,
		arg.Name,
		arg.ClearLogo,
		arg.Logo,
		arg.ID,
	)
	return err
}

const updateTeamStats = `-- name: UpdateTeamStats :exec
UPDATE "organization"
SET "rankingAverage" = COALESCE($1, "rankingAverage"),
    "pointsAverage" = COALESCE($2, "pointsAverage"),
    "seasonRank" = COALESCE($3, "seasonRank"),
    "averagePointsPerEvent" = COALESCE($4, "averagePointsPerEvent")
WHERE id = $5
`

type UpdateTeamStatsParams struct {
	RankingAverage        sql.NullFloat64
	PointsAverage         sql.NullFloat64
	SeasonRank            sql.NullInt32
	AveragePointsPerEvent sql.NullFloat64
	ID                    string
}

// Team stats update. Null leaves the column unchanged (no explicit-null
// clearing exists for stats, so plain COALESCE is lossless).
func (q *Queries) UpdateTeamStats(ctx context.Context, arg UpdateTeamStatsParams) error {
	_, err := q.db.ExecContext(ctx, updateTeamStats,
		arg.RankingAverage,
		arg.PointsAverage,
		arg.SeasonRank,
		arg.AveragePointsPerEvent,
		arg.ID,
	)
	return err
}

const userIDByID = `-- name: UserIDByID :one
SELECT id FROM "user" WHERE id = $1
`

func (q *Queries) UserIDByID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, userIDByID, id)
	err := row.Scan(&id)
	return id, err
}
