// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteSessionByToken = `-- name: DeleteSessionByToken :exec
DELETE FROM "session" WHERE "token" = $1
`

// Session delete (used by compat.go Logout).
func (q *Queries) DeleteSessionByToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByToken, token)
	return err
}

const deleteVerificationByIdentifier = `-- name: DeleteVerificationByIdentifier :exec
DELETE FROM "verification" WHERE "identifier" = $1
`

// Verification delete (used by compat.go).
func (q *Queries) DeleteVerificationByIdentifier(ctx context.Context, identifier string) error {
	_, err := q.db.ExecContext(ctx, deleteVerificationByIdentifier, identifier)
	return err
}

const eventAdminExists = `-- name: EventAdminExists :one
SELECT EXISTS(SELECT 1 FROM "event_admin" WHERE "eventId" = $1 AND "userId" = $2)
`

type EventAdminExistsParams struct {
	EventId string
	UserId  string
}

// Event admin check (used by getEventActor in rbac.go).
func (q *Queries) EventAdminExists(ctx context.Context, arg EventAdminExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, eventAdminExists, arg.EventId, arg.UserId)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getDiscordAccountID = `-- name: GetDiscordAccountID :one
SELECT "accountId" FROM "account" WHERE "userId" = $1 AND "providerId" = 'discord' ORDER BY "updatedAt" DESC LIMIT 1
`

// Discord account lookup (used by slugify in slugs.go).
func (q *Queries) GetDiscordAccountID(ctx context.Context, userid string) (string, error) {
	row := q.db.QueryRowContext(ctx, getDiscordAccountID, userid)
	var accountId string
	err := row.Scan(&accountId)
	return accountId, err
}

const getMemberRole = `-- name: GetMemberRole :one
SELECT role FROM "member" WHERE "organizationId" = $1 AND "userId" = $2
`

type GetMemberRoleParams struct {
	OrganizationId string
	UserId         string
}

// Member role lookup (used by getMemberRole in rbac.go).
func (q *Queries) GetMemberRole(ctx context.Context, arg GetMemberRoleParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getMemberRole, arg.OrganizationId, arg.UserId)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getOrgBySlug = `-- name: GetOrgBySlug :one
SELECT id FROM "organization" WHERE slug = $1
`

// Organization lookup by slug (used by slugs.go).
func (q *Queries) GetOrgBySlug(ctx context.Context, slug string) (string, error) {
	row := q.db.QueryRowContext(ctx, getOrgBySlug, slug)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getUserBySlug = `-- name: GetUserBySlug :one
SELECT id FROM "user" WHERE slug = $1
`

// User lookup by slug (used by Slug collision checks in slugs.go).
func (q *Queries) GetUserBySlug(ctx context.Context, slug sql.NullString) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserBySlug, slug)
	var id string
	err := row.Scan(&id)
	return id, err
}

const updateUserPlaceholder = `-- name: UpdateUserPlaceholder :exec
UPDATE "user" SET name = $1 WHERE id = $2
`

type UpdateUserPlaceholderParams struct {
	Name string
	ID   string
}

// Update user placeholder (used by UpdateUser). Dynamic SQL is used in Go for
// the column-list; this query is only a placeholder to verify the
// table shape. Keep the raw db.Exec in users.go for now.
func (q *Queries) UpdateUserPlaceholder(ctx context.Context, arg UpdateUserPlaceholderParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPlaceholder, arg.Name, arg.ID)
	return err
}

const userSlugExists = `-- name: UserSlugExists :one
SELECT id FROM "user" WHERE slug = $1
`

// User slug collision check (used by UpdateUser).
func (q *Queries) UserSlugExists(ctx context.Context, slug sql.NullString) (string, error) {
	row := q.db.QueryRowContext(ctx, userSlugExists, slug)
	var id string
	err := row.Scan(&id)
	return id, err
}
