// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: eventmanager.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const deleteEventLadderByUser = `-- name: DeleteEventLadderByUser :exec
DELETE FROM "event_ladder_entry" WHERE "eventId" = $1 AND "userId" = $2
`

type DeleteEventLadderByUserParams struct {
	EventId string
	UserId  string
}

// Delete event ladder entries for a user (used by RemoveMemberFromEvent).
func (q *Queries) DeleteEventLadderByUser(ctx context.Context, arg DeleteEventLadderByUserParams) error {
	_, err := q.db.ExecContext(ctx, deleteEventLadderByUser, arg.EventId, arg.UserId)
	return err
}

const deleteEventMembersByUser = `-- name: DeleteEventMembersByUser :exec
DELETE FROM "event_member" WHERE "eventId" = $1 AND "userId" = $2
`

type DeleteEventMembersByUserParams struct {
	EventId string
	UserId  string
}

// Delete all event members for a user (used by RemoveMemberFromEvent).
func (q *Queries) DeleteEventMembersByUser(ctx context.Context, arg DeleteEventMembersByUserParams) error {
	_, err := q.db.ExecContext(ctx, deleteEventMembersByUser, arg.EventId, arg.UserId)
	return err
}

const deleteEventPointsByUser = `-- name: DeleteEventPointsByUser :exec
DELETE FROM "event_points_entry" WHERE "eventId" = $1 AND "userId" = $2
`

type DeleteEventPointsByUserParams struct {
	EventId string
	UserId  string
}

// Delete event points entries for a user (used by RemoveMemberFromEvent).
func (q *Queries) DeleteEventPointsByUser(ctx context.Context, arg DeleteEventPointsByUserParams) error {
	_, err := q.db.ExecContext(ctx, deleteEventPointsByUser, arg.EventId, arg.UserId)
	return err
}

const deleteRaceEvent = `-- name: DeleteRaceEvent :exec
DELETE FROM "race_event" WHERE id = $1
`

// Delete race event.
func (q *Queries) DeleteRaceEvent(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRaceEvent, id)
	return err
}

const deleteRaceEventMember = `-- name: DeleteRaceEventMember :exec
DELETE FROM "race_event_member" WHERE "raceEventId"=$1 AND "userId"=$2
`

type DeleteRaceEventMemberParams struct {
	RaceEventId string
	UserId      string
}

// Delete race event member (used by RemoveRaceEventMember, JoinRaceEvent).
func (q *Queries) DeleteRaceEventMember(ctx context.Context, arg DeleteRaceEventMemberParams) error {
	_, err := q.db.ExecContext(ctx, deleteRaceEventMember, arg.RaceEventId, arg.UserId)
	return err
}

const deleteRaceEventMemberByEvent = `-- name: DeleteRaceEventMemberByEvent :exec
DELETE FROM "race_event_member" WHERE "userId"=$1 AND "raceEventId" IN
    (SELECT id FROM "race_event" WHERE "eventId"=$2)
`

type DeleteRaceEventMemberByEventParams struct {
	UserId  string
	EventId string
}

// Delete race event member by user and event (used by LeaveRaceEvent).
func (q *Queries) DeleteRaceEventMemberByEvent(ctx context.Context, arg DeleteRaceEventMemberByEventParams) error {
	_, err := q.db.ExecContext(ctx, deleteRaceEventMemberByEvent, arg.UserId, arg.EventId)
	return err
}

const eventExists = `-- name: EventExists :one
SELECT EXISTS(SELECT 1 FROM "event" WHERE id = $1)
`

// Event exists check.
func (q *Queries) EventExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRowContext(ctx, eventExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const eventMemberExists = `-- name: EventMemberExists :one
SELECT EXISTS(SELECT 1 FROM "event_member" WHERE "eventId"=$1 AND "userId"=$2)
`

type EventMemberExistsParams struct {
	EventId string
	UserId  string
}

// Event member lookup.
func (q *Queries) EventMemberExists(ctx context.Context, arg EventMemberExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, eventMemberExists, arg.EventId, arg.UserId)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const eventMemberExistsForJoin = `-- name: EventMemberExistsForJoin :one
SELECT EXISTS(SELECT 1 FROM "event_member" WHERE "eventId"=$1 AND "userId"=$2)
`

type EventMemberExistsForJoinParams struct {
	EventId string
	UserId  string
}

// Event member for JoinEvent.
func (q *Queries) EventMemberExistsForJoin(ctx context.Context, arg EventMemberExistsForJoinParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, eventMemberExistsForJoin, arg.EventId, arg.UserId)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getActiveRaceCountForUser = `-- name: GetActiveRaceCountForUser :one
SELECT COUNT(*) FROM "race_event_member" m JOIN "race_event" r ON r.id = m."raceEventId"
WHERE m."userId"=$1 AND r."eventId"=$2
`

type GetActiveRaceCountForUserParams struct {
	UserId  string
	EventId string
}

// Active race count for a user in an event (used by LeaveRaceEvent).
func (q *Queries) GetActiveRaceCountForUser(ctx context.Context, arg GetActiveRaceCountForUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getActiveRaceCountForUser, arg.UserId, arg.EventId)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getEventMemberCount = `-- name: GetEventMemberCount :one
SELECT COUNT(*) FROM "event_member" WHERE "eventId" = $1
`

// Event member count (used by AddEventMember for participant limit).
func (q *Queries) GetEventMemberCount(ctx context.Context, eventid string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getEventMemberCount, eventid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getEventScheduleByID = `-- name: GetEventScheduleByID :one
SELECT id, "eventId", title, "startsAt", "endsAt", location, "createdAt"
FROM "event_schedule" WHERE id = $1
`

// Event scheduling row lookup.
func (q *Queries) GetEventScheduleByID(ctx context.Context, id string) (EventSchedule, error) {
	row := q.db.QueryRowContext(ctx, getEventScheduleByID, id)
	var i EventSchedule
	err := row.Scan(
		&i.ID,
		&i.EventId,
		&i.Title,
		&i.StartsAt,
		&i.EndsAt,
		&i.Location,
		&i.CreatedAt,
	)
	return i, err
}

const getMaxRaceSequence = `-- name: GetMaxRaceSequence :one
SELECT MAX(sequence) FROM "race_event" WHERE "eventId" = $1
`

// Max sequence for a race event (used by CreateRaceEvent).
func (q *Queries) GetMaxRaceSequence(ctx context.Context, eventid string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMaxRaceSequence, eventid)
	var max interface{}
	err := row.Scan(&max)
	return max, err
}

const getRaceEventMemberCount = `-- name: GetRaceEventMemberCount :one
SELECT COUNT(*) FROM "race_event_member" WHERE "raceEventId" = $1
`

// Race event member count for limit checks.
func (q *Queries) GetRaceEventMemberCount(ctx context.Context, raceeventid string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getRaceEventMemberCount, raceeventid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserClassTier = `-- name: GetUserClassTier :one
SELECT "classTier" FROM "user" WHERE id = $1
`

// User class tier lookup (used by AddRaceEventMember, JoinRaceEvent).
func (q *Queries) GetUserClassTier(ctx context.Context, id string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getUserClassTier, id)
	var classTier interface{}
	err := row.Scan(&classTier)
	return classTier, err
}

const insertEventMember = `-- name: InsertEventMember :exec
INSERT INTO "event_member" (id, "eventId", "userId", "createdAt")
VALUES ($1, $2, $3, $4) ON CONFLICT ("eventId", "userId") DO NOTHING
`

type InsertEventMemberParams struct {
	ID        string
	EventId   string
	UserId    string
	CreatedAt time.Time
}

// Create event member row.
func (q *Queries) InsertEventMember(ctx context.Context, arg InsertEventMemberParams) error {
	_, err := q.db.ExecContext(ctx, insertEventMember,
		arg.ID,
		arg.EventId,
		arg.UserId,
		arg.CreatedAt,
	)
	return err
}

const insertEventSchedule = `-- name: InsertEventSchedule :exec
INSERT INTO "event_schedule" (id, "eventId", title, "startsAt", "endsAt", location, "createdAt")
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertEventScheduleParams struct {
	ID        string
	EventId   string
	Title     sql.NullString
	StartsAt  time.Time
	EndsAt    sql.NullTime
	Location  sql.NullString
	CreatedAt time.Time
}

// Create event schedule row.
func (q *Queries) InsertEventSchedule(ctx context.Context, arg InsertEventScheduleParams) error {
	_, err := q.db.ExecContext(ctx, insertEventSchedule,
		arg.ID,
		arg.EventId,
		arg.Title,
		arg.StartsAt,
		arg.EndsAt,
		arg.Location,
		arg.CreatedAt,
	)
	return err
}

const insertRaceEvent = `-- name: InsertRaceEvent :exec
INSERT INTO "race_event" (id, "eventId", name, sequence, "distanceMeters", "trackType",
    location, "scoringType", grade, "classRestriction", "startsAt", "endsAt",
    "participantLimit", "createdAt", "updatedAt")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
`

type InsertRaceEventParams struct {
	ID               string
	EventId          string
	Name             string
	Sequence         int32
	DistanceMeters   int32
	TrackType        string
	Location         string
	ScoringType      sql.NullInt16
	Grade            sql.NullString
	ClassRestriction interface{}
	StartsAt         sql.NullTime
	EndsAt           sql.NullTime
	ParticipantLimit sql.NullInt32
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

// Create race event row.
func (q *Queries) InsertRaceEvent(ctx context.Context, arg InsertRaceEventParams) error {
	_, err := q.db.ExecContext(ctx, insertRaceEvent,
		arg.ID,
		arg.EventId,
		arg.Name,
		arg.Sequence,
		arg.DistanceMeters,
		arg.TrackType,
		arg.Location,
		arg.ScoringType,
		arg.Grade,
		arg.ClassRestriction,
		arg.StartsAt,
		arg.EndsAt,
		arg.ParticipantLimit,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listRaceEventMembers = `-- name: ListRaceEventMembers :many
SELECT m."userId", COALESCE(u."vrchatUsername", u.name), u."classTier"
FROM "race_event_member" m JOIN "user" u ON u.id = m."userId"
WHERE m."raceEventId" = $1
`

type ListRaceEventMembersRow struct {
	UserId         string
	VrchatUsername string
	ClassTier      interface{}
}

// Race members for a race.
func (q *Queries) ListRaceEventMembers(ctx context.Context, raceeventid string) ([]ListRaceEventMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listRaceEventMembers, raceeventid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRaceEventMembersRow
	for rows.Next() {
		var i ListRaceEventMembersRow
		if err := rows.Scan(&i.UserId, &i.VrchatUsername, &i.ClassTier); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const raceEventMemberExists = `-- name: RaceEventMemberExists :one
SELECT EXISTS(SELECT 1 FROM "event_member" WHERE "eventId"=$1 AND "userId"=$2)
`

type RaceEventMemberExistsParams struct {
	EventId string
	UserId  string
}

// Race member exists check (used by AddRaceEventMember).
func (q *Queries) RaceEventMemberExists(ctx context.Context, arg RaceEventMemberExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, raceEventMemberExists, arg.EventId, arg.UserId)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateEventSignupsLocked = `-- name: UpdateEventSignupsLocked :exec
UPDATE "event" SET "signupsLocked" = $1, "updatedAt" = $2 WHERE id = $3
`

type UpdateEventSignupsLockedParams struct {
	SignupsLocked bool
	UpdatedAt     time.Time
	ID            string
}

// Signups lock update.
func (q *Queries) UpdateEventSignupsLocked(ctx context.Context, arg UpdateEventSignupsLockedParams) error {
	_, err := q.db.ExecContext(ctx, updateEventSignupsLocked, arg.SignupsLocked, arg.UpdatedAt, arg.ID)
	return err
}

const updateRaceEvent = `-- name: UpdateRaceEvent :exec
UPDATE "race_event" SET name=$1, sequence=$2, "distanceMeters"=$3, "trackType"=$4,
    location=$5, "scoringType"=$6, grade=$7, "classRestriction"=$8, "startsAt"=$9,
    "endsAt"=$10, "participantLimit"=$11, "updatedAt"=$12 WHERE id=$13
`

type UpdateRaceEventParams struct {
	Name             string
	Sequence         int32
	DistanceMeters   int32
	TrackType        string
	Location         string
	ScoringType      sql.NullInt16
	Grade            sql.NullString
	ClassRestriction interface{}
	StartsAt         sql.NullTime
	EndsAt           sql.NullTime
	ParticipantLimit sql.NullInt32
	UpdatedAt        time.Time
	ID               string
}

// Update race event (used by UpdateRaceEvent).
func (q *Queries) UpdateRaceEvent(ctx context.Context, arg UpdateRaceEventParams) error {
	_, err := q.db.ExecContext(ctx, updateRaceEvent,
		arg.Name,
		arg.Sequence,
		arg.DistanceMeters,
		arg.TrackType,
		arg.Location,
		arg.ScoringType,
		arg.Grade,
		arg.ClassRestriction,
		arg.StartsAt,
		arg.EndsAt,
		arg.ParticipantLimit,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateRaceSequence = `-- name: UpdateRaceSequence :exec
UPDATE "race_event" SET sequence = $1 WHERE id = $2
`

type UpdateRaceSequenceParams struct {
	Sequence int32
	ID       string
}

// Update race event sequence (used by ReorderRaceEvents).
func (q *Queries) UpdateRaceSequence(ctx context.Context, arg UpdateRaceSequenceParams) error {
	_, err := q.db.ExecContext(ctx, updateRaceSequence, arg.Sequence, arg.ID)
	return err
}
