// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Account struct {
	ID                    string
	AccountId             string
	ProviderId            string
	UserId                string
	AccessToken           sql.NullString
	RefreshToken          sql.NullString
	IdToken               sql.NullString
	AccessTokenExpiresAt  sql.NullTime
	RefreshTokenExpiresAt sql.NullTime
	Scope                 sql.NullString
	Password              sql.NullString
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type Dataset struct {
	ID         string
	EventId    string
	Source     string
	Rows       int32
	Status     interface{}
	ImportedAt sql.NullTime
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Event struct {
	ID                              string
	Name                            string
	Description                     sql.NullString
	OrganizationId                  sql.NullString
	ScoringType                     int16
	ClassRestriction                interface{}
	CreatedAt                       time.Time
	UpdatedAt                       time.Time
	OwnerType                       interface{}
	OwnerUserId                     sql.NullString
	Status                          interface{}
	GranularParticipation           bool
	SignupsLocked                   bool
	CustomScoringTables             pqtype.NullRawMessage
	ScoringRulesMode                sql.NullString
	ScheduledAt                     sql.NullTime
	ParticipantLimit                sql.NullInt32
	MaxConcurrentRaceParticipations sql.NullInt32
}

type EventAdmin struct {
	ID        string
	EventId   string
	UserId    string
	CreatedAt time.Time
}

type EventLadderEntry struct {
	ID        string
	EventId   string
	UserId    string
	Elo       int32
	Wins      int32
	Losses    int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type EventMember struct {
	ID        string
	EventId   string
	UserId    string
	CreatedAt time.Time
}

type EventPointsEntry struct {
	ID        string
	EventId   string
	UserId    string
	Points    int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type EventSchedule struct {
	ID        string
	EventId   string
	Title     sql.NullString
	StartsAt  time.Time
	EndsAt    sql.NullTime
	Location  sql.NullString
	CreatedAt time.Time
}

type Invitation struct {
	ID             string
	OrganizationId string
	Email          string
	Role           string
	Status         string
	ExpiresAt      time.Time
	CreatedAt      time.Time
	InviterId      string
}

type Member struct {
	ID             string
	OrganizationId string
	UserId         string
	Role           string
	CreatedAt      time.Time
}

type Organization struct {
	ID                    string
	Name                  string
	Slug                  string
	Logo                  sql.NullString
	Metadata              pqtype.NullRawMessage
	CreatedAt             time.Time
	UpdatedAt             sql.NullTime
	RankingAverage        sql.NullFloat64
	PointsAverage         sql.NullFloat64
	SeasonRank            sql.NullInt32
	AveragePointsPerEvent sql.NullFloat64
}

type RaceEvent struct {
	ID               string
	EventId          string
	Name             string
	Sequence         int32
	DistanceMeters   int32
	TrackType        string
	Location         string
	ScoringType      sql.NullInt16
	ClassRestriction interface{}
	StartsAt         sql.NullTime
	EndsAt           sql.NullTime
	CreatedAt        time.Time
	UpdatedAt        time.Time
	Grade            sql.NullString
	ParticipantLimit sql.NullInt32
}

type RaceEventMember struct {
	ID          string
	RaceEventId string
	UserId      string
	CreatedAt   time.Time
}

type RaceResult struct {
	ID           string
	RaceEventId  string
	UserId       string
	Position     sql.NullInt32
	Points       int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
	GateNumber   sql.NullInt16
	FinishTime   sql.NullString
	Margin       sql.NullString
	PassingOrder sql.NullString
	Final3F      sql.NullString
	ResultStatus sql.NullString
}

type ScoreCalcState struct {
	EventId            string
	LatestGeneration   int32
	AcceptedGeneration int32
	UpdatedAt          time.Time
}

type ScoreCalcTask struct {
	ID               string
	EventId          string
	Status           string
	Attempts         int32
	CompletedAt      sql.NullTime
	Generation       int32
	LastError        sql.NullString
	RequestedAt      time.Time
	RequestedUserIds pqtype.NullRawMessage
	ResultChecksum   sql.NullString
	StartedAt        sql.NullTime
}

type Session struct {
	ID                   string
	ExpiresAt            time.Time
	Token                string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	IpAddress            sql.NullString
	UserAgent            sql.NullString
	UserId               string
	ActiveOrganizationId sql.NullString
}

type User struct {
	ID             string
	Name           string
	Email          string
	EmailVerified  bool
	Image          sql.NullString
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Biography      sql.NullString
	CareerOverview sql.NullString
	ClassTier      interface{}
	SiteRole       interface{}
	VrchatUsername sql.NullString
	Slug           sql.NullString
}

type Verification struct {
	ID         string
	Identifier string
	Value      string
	ExpiresAt  time.Time
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}
